version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: teamdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iloveyou044
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  team-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://postgres:iloveyou044@postgres:5432/teamdb?sslmode=disable
      - JWT_SECRET=your-secret-key-change-this-in-production
    depends_on:
      - postgres

volumes:
  postgres_data:
